---
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo-istio-system
  labels:
    name: bookinfo-istio-system
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: bookinfo-istio-system
spec:
  proxy:
    networking:
      trafficControl:
        inbound:
          excludedPorts:
            - 15020
  version: v2.1
  tracing:
    sampling: 100
    type: Jaeger
  addons:
    prometheus:
      scrape: true
    jaeger:
      name: jaeger
      install:
        storage:
          type: Elasticsearch
        ingress:
          enabled: true
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
  runtime:
    defaults:
      container:
        imagePullPolicy: Always
    components:
      tracing.jaeger.elasticsearch: # only supports resources and image name
        container:
          resources: {}
  security:
    trust:
    manageNetworkPolicy: true
    dataPlane:
      mtls: true
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: bookinfo-istio-system
spec:
  members:
    - bookinfo
---