apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - reviews.yaml
  - ratings.yaml
  - details.yaml
  - productpage.yaml
  - gateway.yaml
bases:
  - ../../../bases
