apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - services
  - reviews.yaml
  - ratings.yaml
  - details.yaml
  - productpage.yaml
  - gateway.yaml
  - namespace.yaml
  - keycloak.yaml