apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: bookinfo-istio-system
spec:
  proxy:
    networking:
      trafficControl:
        inbound:
          excludedPorts:
            - 15020
  tracing:
    sampling: 100
    type: Jaeger
  addons:
    prometheus:
      scrape: true
    jaeger:
      name: jaeger
      install:
        storage:
          type: Elasticsearch
        ingress:
          enabled: true
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
  runtime:
    defaults:
      container:
        imagePullPolicy: Always
    components:
      tracing.jaeger.elasticsearch: # only supports resources and image name
        container:
          resources: {}
  security:
    trust:
    manageNetworkPolicy: true
    dataPlane:
      mtls: true # For outgoing service calls see PeerAuthentication: https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/ossm-security.html#ossm-security-mtls-sidecars-incoming-services_ossm-security
    controlPlane:
      tls:
        minProtocolVersion: TLS_AUTO
    certificateAuthority:
      type: Istiod
      istiod:
        type: PrivateKey
        privateKey:
          rootCADir:  /etc/cacerts
---