apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - destination-rule.yaml
  - service.yaml
  - service-account.yaml
  - virtual-service.yaml
#  - grafana.yaml
#  - prometheus.yaml