apiVersion: v1
kind: DeploymentConfig
metadata:
  name: patch-me
  namespace: bookinfo
spec:
  replicas: 1
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling