- op: add
  path: /metadata
  value:
    labels:
      app: reviews
      version: v2
- op: add
  path: /spec/selector
  value:
    app: reviews
    version: v2
- op: add
  path: /spec/triggers
  value:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - reviews
        from:
          kind: ImageStreamTag
          name: examples-bookinfo-reviews-v2:2.1
      type: ImageChange
- op: add
  path: /spec/template
  value:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          image: examples-bookinfo-reviews-v2
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_DIR
              value: "/tmp/logs"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: wlp-output
              mountPath: /opt/ibm/wlp/output
      volumes:
        - name: wlp-output
          emptyDir: {}
        - name: tmp
          emptyDir: {}
- op: replace
  path: /metadata/name
  value: reviews-v2
